In [1]:
import numpy as np

<b>Exercise 1</b>

In [22]:
array = np.array(np.random.randint(-5, 10, 9)).reshape(3, 3)
array

array([[ 4, -2,  6],
       [ 4, -2,  2],
       [ 6,  7, -3]])

determinant = np.linalg.det(array)
print(f"Determinant: {determinant}")

In [24]:
inverse = np.linalg.inv(array)
print(f"Inverse matrix:\n{inverse}")

Inverse matrix:
[[-0.05   0.225  0.05 ]
 [ 0.15  -0.3    0.1  ]
 [ 0.25  -0.25   0.   ]]


<b>Exercise 2<b/>

In [25]:
array = np.array(np.random.randint(1, 100, 50))
array

array([94,  7, 22, 83, 49, 70, 44, 10,  8, 57, 68, 12, 42, 24, 33, 70, 61,
       69, 43, 51,  6, 15, 12, 99, 38, 34, 97,  4, 40, 36, 46, 83, 56, 21,
       28,  6, 69, 75, 74, 74, 97, 14, 57, 36, 94, 82, 83, 57, 74,  5])

In [31]:
print(f"Mean: {np.mean(array)}")
print(f"Median: {np.median(array)}")
print(f"Standard Deviation: {np.std(array)}")

Mean: 48.58
Median: 47.5
Standard Deviation: 29.03521310409138


<b>Exercise 3</b>

In [4]:
dates = np.arange('2023-01', '2023-02', dtype='datetime64[D]')
print("January 2023 Dates:\n", dates)

January 2023 Dates:
 ['2023-01-01' '2023-01-02' '2023-01-03' '2023-01-04' '2023-01-05'
 '2023-01-06' '2023-01-07' '2023-01-08' '2023-01-09' '2023-01-10'
 '2023-01-11' '2023-01-12' '2023-01-13' '2023-01-14' '2023-01-15'
 '2023-01-16' '2023-01-17' '2023-01-18' '2023-01-19' '2023-01-20'
 '2023-01-21' '2023-01-22' '2023-01-23' '2023-01-24' '2023-01-25'
 '2023-01-26' '2023-01-27' '2023-01-28' '2023-01-29' '2023-01-30'
 '2023-01-31']


In [ ]:
FALTA

In [2]:
start_date = np.datetime64('2023-01-01')
end_date = np.datetime64('2023-02-01')

dates = np.arange(start_date, end_date, dtype='datetime64[D]')
format_str = '%Y/%m/%d'

formatted_dates = dates.astype(str)[:, :10]  # Select only date part

# Print the original and formatted dates
print("Original Dates:")
print(dates)

print("\nFormatted Dates:")
print(formatted_dates)

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

<b>Exercise 4</b>

In [52]:
array = np.array(np.random.randint(0, 50, 25)).reshape(5,5)
array

array([[ 7,  5,  9, 21, 37],
       [22, 35, 49,  4, 32],
       [37, 10, 23,  5, 19],
       [36, 27,  6, 49, 22],
       [29, 36, 46, 15, 20]])

In [55]:
array[:, 2].sum()

133

In [56]:
array[2, :].mean()

18.8

<b>Exercise 5</b>

Images are represented as multi-dimensional arrays (ndarrays).

An image consists of pixels arranged in rows and columns.
Each pixel has a specific intensity value representing its color or brightness.
NumPy arrays perfectly capture this grid-like structure.

A grayscale image typically uses a 2D array.
Each element in the array corresponds to the intensity (often 0 for black, 255 for white, and values in between for shades of gray) of a single pixel.
The first dimension represents the rows (height) of the image.
The second dimension represents the columns (width) of the image.
Color Images:

Color images require more information than grayscale.
They typically use a 3D array.
The first two dimensions (same as grayscale) represent rows and columns.
The third dimension represents color channels (usually Red, Green, and Blue - RGB).
Each element in this third dimension is a value between 0 and 255 representing the intensity of that specific color channel for the pixel.

In [57]:
grayscale_image = np.random.randint(0, 256, size=(5, 5), dtype=np.uint8)  

print(grayscale_image)

[[  4 208 103 209  88]
 [158 208 170 157  42]
 [133  66  15 228  34]
 [255 134  16 115 146]
 [ 66 215 124 192 136]]


<b>Exercise 6</b>

In [58]:
# Productivity scores of employees before the training program
productivity_before = np.random.normal(loc=50, scale=10, size=30)

# Productivity scores of the same employees after the training program
productivity_after = productivity_before + np.random.normal(loc=5, scale=3, size=30)

# Your task is to formulate a hypothesis regarding the training program's effectiveness 
# and test it using basic statistical functions in NumPy.

<b>Exercise 7</b>

In [4]:
array1 = np.array(np.random.randint(0, 50, 10))
array2 = np.array(np.random.randint(0, 50, 10))

greater_elements = array1 > array2

print(array1)
print(array2)
print(greater_elements)

[10 47 31 13 14 24 34 37 28 34]
[46 38 45 20 17 14  7 34 42 21]
[False  True False False False  True  True  True False  True]


<b>Exercise 8</b>

In [16]:
start_date = np.datetime64('2023-01-01')
end_date = np.datetime64('2024-01-01')
dates = np.arange(start_date, end_date, dtype='datetime64[D]')
dates[:90]
dates[90:181]
dates[181:273]
dates[273:365]

array(['2023-10-01', '2023-10-02', '2023-10-03', '2023-10-04',
       '2023-10-05', '2023-10-06', '2023-10-07', '2023-10-08',
       '2023-10-09', '2023-10-10', '2023-10-11', '2023-10-12',
       '2023-10-13', '2023-10-14', '2023-10-15', '2023-10-16',
       '2023-10-17', '2023-10-18', '2023-10-19', '2023-10-20',
       '2023-10-21', '2023-10-22', '2023-10-23', '2023-10-24',
       '2023-10-25', '2023-10-26', '2023-10-27', '2023-10-28',
       '2023-10-29', '2023-10-30', '2023-10-31', '2023-11-01',
       '2023-11-02', '2023-11-03', '2023-11-04', '2023-11-05',
       '2023-11-06', '2023-11-07', '2023-11-08', '2023-11-09',
       '2023-11-10', '2023-11-11', '2023-11-12', '2023-11-13',
       '2023-11-14', '2023-11-15', '2023-11-16', '2023-11-17',
       '2023-11-18', '2023-11-19', '2023-11-20', '2023-11-21',
       '2023-11-22', '2023-11-23', '2023-11-24', '2023-11-25',
       '2023-11-26', '2023-11-27', '2023-11-28', '2023-11-29',
       '2023-11-30', '2023-12-01', '2023-12-02', '2023-

<b>Exercise 9</b>

In [17]:
df = pd.DataFrame([[1, 2, 3], [4, 5, 6], [7, 8, 9]], columns=['Columna1', 'Columna2', 'Columna3'])
array_numpy = np.array(df.values)

# Imprimir el array NumPy
print(array_numpy)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
array_numpy = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array_numpy

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
columns=['Columna1', 'Columna2', 'Columna3']
df = pd.DataFrame(array_numpy, columns=columns)
df

Columna1  Columna2  Columna3
0         1         2         3
1         4         5         6
2         7         8         9