In [2]:
import numpy as np

<b> Exercise 1</b>

In [5]:
array = np.array(np.arange(0,10))

In [6]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

<b> Exercise 2</b>

In [8]:
l = [3.14, 2.17, 0, 1, 2]
array = np.array(l)
array.astype(np.int32)

array([3, 2, 0, 1, 2])

<b> Exercise 3</b>

In [10]:
array = np.array(np.arange(1, 10)).reshape(3,3)
array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

<b> Exercise 4</b>

In [13]:
array = np.array(np.random.rand(20)).reshape(4, 5)
array

array([[0.59555629, 0.72024754, 0.82991331, 0.26138672, 0.13766819],
       [0.71552692, 0.19906504, 0.01568942, 0.84124199, 0.94852822],
       [0.8463332 , 0.62205581, 0.40753657, 0.85691985, 0.45294425],
       [0.42101207, 0.46887646, 0.24003523, 0.66722069, 0.51244804]])

<b> Exercise 5</b>

In [16]:
array = np.array(np.random.randint(0, 30, 10)).reshape(2, 5)
array

array([[27,  8, 20, 24, 29],
       [20, 19, 24, 17, 27]])

In [17]:
array[1, :]

array([20, 19, 24, 17, 27])

<b> Exercise 6</b>

In [18]:
array = np.array(np.random.randint(0, 10, 10))
array

array([5, 9, 9, 4, 4, 3, 5, 9, 7, 9])

In [19]:
np.flip(array, 0)

array([9, 7, 9, 5, 3, 4, 4, 9, 9, 5])

<b>Exercise 7</b>

In [20]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

<b>Exercise 8</b>

In [24]:
array = np.array(np.arange(10))
print(array.mean())
print(array.sum())

4.5
45


<b> Exercise 9</b>

In [26]:
array = np.arange(1, 21).reshape(4, 5)
array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

<b>Exercise 10</b>

In [30]:
array = np.array(np.arange(10))
array2 = [n for n in array if n%2!=0]

In [31]:
print(array)
print(array2)

[0 1 2 3 4 5 6 7 8 9]
[1, 3, 5, 7, 9]
